/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    InseratList: typeof import('./components/InseratList.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./components/Filter/SearchForm.vue')['default']
    SelectForm: typeof import('./components/Filter/SelectForm.vue')['default']
    SortForm: typeof import('./components/Filter/SortForm.vue')['default']
  }
}
